services:
  app:
    build: .
    container_name: fastapi_forum_app_container
    environment:
      POSTGRES_HOST: postgres_forum_container
      POSTGRES_PORT: 5432
      POSTGRES_USER: test_forum_database
      POSTGRES_PASS: test_forum_database
      POSTGRES_NAME: test_forum_database
      REDIS_HOST: redis_forum_container
      REDIS_PORT: 6379
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy

  postgres:
    image: postgres:16.1-alpine
    container_name: postgres_forum_container
    restart: always
    environment:
      POSTGRES_USER: test_forum_database
      POSTGRES_PASSWORD: test_forum_database
      POSTGRES_DB: test_forum_database
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U test_forum_database"]
      interval: 5s
      timeout: 5s
      retries: 5

  pgadmin4:
    image: elestio/pgadmin
    restart: always
    environment:
      PGADMIN_LISTEN_PORT: 8080
      PGADMIN_DEFAULT_EMAIL: example_email@gmail.com
      PGADMIN_DEFAULT_PASSWORD: password
    ports:
      - "8080:8080"
    volumes:
      - ./servers.json:/pgadmin4/servers.json

  redis:
    image: redis:7.4.5-alpine3.21
    container_name: redis_forum_container
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 3s
      retries: 5
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: